// app/api/admin/ml-accuracy/route.ts

/**
 * ============================================================================
 * ML ACCURACY API — ADMIN ENDPOINT
 * ============================================================================
 *
 * Feeds the ML Health Dashboard page with three data streams:
 *
 *   1. accuracy  — ml_model_accuracy table
 *      Stores per-run metric values (silhouette score, MAPE, avg lift, etc.)
 *      written by the Python ML pipeline after each pipeline execution.
 *      Fetches the 50 most recent rows so the dashboard can compute trends
 *      by comparing the latest run to the previous run per metric.
 *
 *   2. jobs — ml_job_metrics table
 *      Stores per-job execution metadata: run time in ms, records processed,
 *      success/failure status, and any error messages.
 *      Fetches the 30 most recent rows for the job history table.
 *
 *   3. drift_alerts — model_drift_alerts table
 *      Active drift alerts (status = 'active') generated by drift_detection.py
 *      when a model metric deviates beyond its configured warning/critical
 *      thresholds relative to the 4-week rolling average.
 *      Only 'active' alerts are returned; acknowledged/resolved are excluded.
 *
 * AUTH: Admin only. Returns 401/403 if the session is absent or non-admin.
 * CACHE: 2-minute s-maxage with 1-minute stale-while-revalidate so the
 *        dashboard stays fresh without hammering the DB on every page load.
 * ============================================================================
 */

import { NextResponse } from 'next/server'
import { requireAdmin } from '@/lib/auth'

// ─── Types ───────────────────────────────────────────────────────────────────

export interface MLAccuracyRecord {
  id: string
  model_name: 'kmeans_segmentation' | 'holt_winters_forecast' | 'fpgrowth_recommendations'
  metric_name: string
  metric_value: number
  records_evaluated: number
  evaluated_at: string
}

export interface MLJobMetric {
  id: string
  job_name: 'apriori_fbt' | 'kmeans_segmentation' | 'holt_winters_forecast' | 'pagerank_graph' | 'ema_trending'
  execution_time_ms: number
  records_processed: number
  status: 'success' | 'failed' | 'partial'
  error_message: string | null
  created_at: string
}

export interface ModelDriftAlert {
  id: string
  model_name: string
  metric_name: string
  current_value: number
  rolling_avg_value: number
  percent_change: number
  severity: 'warning' | 'critical'
  status: 'active' | 'acknowledged' | 'resolved'
  created_at: string
}

export interface MLDashboardResponse {
  accuracy: MLAccuracyRecord[]
  jobs: MLJobMetric[]
  drift_alerts: ModelDriftAlert[]
}

// ─── GET Handler ─────────────────────────────────────────────────────────────

export async function GET() {
  // 1. Auth gate — admin session required
  const auth = await requireAdmin()
  if (!auth.success) return auth.response

  const supabase = await auth.supabase

  try {
    // 2. Fetch all three datasets in parallel to minimise latency
    const [accuracyRes, jobsRes, driftRes] = await Promise.all([
      // Accuracy logs: 50 most recent across all models and metrics.
      // We fetch 50 (not 20) so the dashboard can compute per-metric trends
      // by comparing the latest value to the one before it, even for models
      // that log multiple metrics per run (silhouette + MAPE + lift).
      supabase
        .from('ml_model_accuracy')
        .select('id, model_name, metric_name, metric_value, records_evaluated, evaluated_at')
        .order('evaluated_at', { ascending: false })
        .limit(50),

      // Job run history: 30 most recent runs across all pipeline jobs.
      // Used to render the job history table and highlight slow/failed runs.
      supabase
        .from('ml_job_metrics')
        .select('id, job_name, execution_time_ms, records_processed, status, error_message, created_at')
        .order('created_at', { ascending: false })
        .limit(30),

      // Active drift alerts only — resolved/acknowledged ones are not surfaced
      // on the dashboard banner. The admin resolves them via a separate action.
      supabase
        .from('model_drift_alerts')
        .select(
          'id, model_name, metric_name, current_value, rolling_avg_value, percent_change, severity, status, created_at'
        )
        .eq('status', 'active')
        .order('created_at', { ascending: false })
        .limit(20),
    ])

    // 3. Check for DB errors on each query independently so one failure
    //    doesn't black out the entire dashboard — return empty arrays instead.
    if (accuracyRes.error) {
      console.error('[ML Accuracy API] Error fetching accuracy logs:', accuracyRes.error)
    }
    if (jobsRes.error) {
      console.error('[ML Accuracy API] Error fetching job metrics:', jobsRes.error)
    }
    if (driftRes.error) {
      console.error('[ML Accuracy API] Error fetching drift alerts:', driftRes.error)
    }

    const body: MLDashboardResponse = {
      accuracy: (accuracyRes.data ?? []) as MLAccuracyRecord[],
      jobs: (jobsRes.data ?? []) as MLJobMetric[],
      drift_alerts: (driftRes.data ?? []) as ModelDriftAlert[],
    }

    return NextResponse.json(body, {
      headers: {
        // Cache for 2 minutes so frequent dashboard refreshes don't hammer the DB.
        // stale-while-revalidate allows the browser to serve the stale response
        // while fetching a fresh one in the background.
        'Cache-Control': 'public, s-maxage=120, stale-while-revalidate=60',
      },
    })
  } catch (error) {
    console.error('[ML Accuracy API] Internal server error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}